version: 0.2

phases:
  install:
    commands:
      - echo Install phase started...
  pre_build:
    commands:
      - echo Started pre_build phase...
      - mkdir -p $CodePipeline/$OutputArtifact
      - ls -al
      - aws --version
      - aws s3 cp --recursive . s3://dockerfile-baseimage/$CodePipeline/$OutputArtifact/
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
